name: flow_server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shared:
    path: ../shared
  get_it: ^7.2.0
  sembast: ^3.1.0+2
  dart_jsonwebtoken: ^2.3.2
#  path: ^1.7.0
dev_dependencies:
  build_runner: ^2.1.1
  lints: ^1.0.1
  test: ^1.17.10
