name: flow_server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shared:
    path: ../shared
  get_it: ^7.2.0
  sembast: ^3.2.0+1
  dart_jsonwebtoken: ^2.4.1
  web_socket_channel: ^2.2.0
  path: ^1.8.2
#  path: ^1.7.0
dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
  test: ^1.21.4
