name: flow_server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shared:
    path: ../shared
  shelf: ^1.1.1
  shelf_router: ^1.0.0
  isar: ^0.4.0
#  path: ^1.7.0
dev_dependencies:
  isar_generator: ^0.4.0
  build_runner: ^2.0.1
  pedantic: ^1.11.0
  test: ^1.17.1
