name: flow_server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shared:
    path: ../shared
  shelf: ^1.2.0
  shelf_router: ^1.1.0
  get_it: ^7.1.4
  sembast: ^3.1.0+2
  dart_jsonwebtoken: ^2.3.0
#  path: ^1.7.0
dev_dependencies:
  shelf_router_generator: ^1.0.0
  build_runner: ^2.0.6
  lints: ^1.0.1
  test: ^1.17.10
