name: shared
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.4.0
  path: ^1.8.0
  sembast: ^3.1.0+2
  equatable: ^2.0.3
  crypto: ^3.0.1
dev_dependencies:
  build_runner: ^2.0.5
  lints: ^1.0.1
  test: ^1.17.9
