name: shared
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  moor: ^4.3.1
  path: ^1.8.0
dev_dependencies:
  moor_generator: ^4.3.1
  build_runner: ^2.0.4
  pedantic: ^1.11.0
  test: ^1.17.4
